### ISSUE TITLE
Empty images appear to be just 0-filled files

### ISSUE THREAD

**Issue by andrewpono** [keirf/FF_Images#1]
Tried to use 1m44.img with my FF Gotek - no floppy found. The file appears to be filled with 0's. Floppy images generated by both WSL and Winimage worked fine.

**Comment by keirf** [comment]
Maybe a better description than Empty would be Unformatted?

**Comment by keirf** [comment]
Supply a formatted IMG or two and I'll make a PC_FAT12 folder.

**Comment by keirf** [comment]
Renamed the folder to Unformatted. Now it should be clear the images within are not FAT formatted. A separate folder should be created with FAT-formatted images.

**Comment by andrewpono** [comment]
Here's the formatted 1.4m file that worked, and 720k untested:
[1m44_fat12.zip](https://github.com/keirf/FF_Images/files/7354919/1m44_fat12.zip)
[720_fat12.zip](https://github.com/keirf/FF_Images/files/7354989/720_fat12.zip)
